Repository wp-cli/wp-cli-bundle, pull requests merged in 2021-03, with the labels that each got.

#263 Handle files with the .php8 extension
  utils/make-phar.php
Labels: bug

#267 Update GHA functional tests workflow
  .github/workflows/testing.yml
  behat.yml
  composer.json
  composer.lock
  utils/make-phar.php
Labels: scope:testing

#273 Update deployment workflow
  .github/workflows/deployment.yml
  .github/workflows/testing.yml
Labels: scope:distribution

#274 Persist version as GHA artifact
  .github/workflows/deployment.yml
Labels: scope:distribution

#275 Adapt reading of version artifact
  .github/workflows/deployment.yml
Labels: scope:distribution

#276 Add PHP 8 back as testing requirement
  .github/workflows/deployment.yml
  .github/workflows/testing.yml
Labels: scope:testing
