Repository wp-cli/wp-cli-bundle, pull requests merged in 2023-08, with the labels that each got.

#564 Update composer.lock (2023-08-04)
  composer.lock
Labels: scope:distribution

#565 Update branch name in wp-cli-updatedeb.sh
  utils/wp-cli-updatedeb.sh
Labels: scope:distribution

#566 Update `composer.lock` (2023-08-17)
  composer.lock
Labels: scope:framework

#569 Update to WPCS v3
  composer.json
  composer.lock
  utils/make-phar-spec.php
  utils/make-phar.php
Labels: scope:testing
