Repository wp-cli/wp-cli-bundle, pull requests merged in 2023-02, with the labels that each got.

#476 Add a new bundle-specific README
  README-new.md
Labels: scope:documentation

#478 Move the new README into its proper location
  README-new.md
  README.md
Labels: scope:documentation

#507 Add a workflow to keep `wp-cli/wp-cli` up to date
  .github/workflows/update-framework.yml
Labels: scope:distribution

#510 Update wp-cli framework
  composer.lock
Labels: scope:framework

#511 Update wp-cli framework
  composer.lock
Labels: scope:framework
