Repository wp-cli/wp-cli-bundle, pull requests merged in 2023-05, with the labels that each got.

#531 Update Composer lock file
  composer.lock
  features/requests.feature
  utils/make-phar.php
Labels: scope:distribution

#532 Update wp-cli/wp-cli
  composer.lock
Labels: bug, scope:distribution

#533 Update wp-cli framework
  composer.lock
Labels: scope:framework

#534 Update wp-cli/wp-cli
  composer.lock
Labels: scope:distribution

#536 Update Composer lock file - 2023-05-05
  composer.lock
Labels: scope:distribution

#537 Skip `update-framework.yml` workflow on forks
  .github/workflows/update-framework.yml
Labels: scope:distribution

#540 Adapt tests for Requests
  composer.json
  composer.lock
  features/requests.feature
Labels: scope:testing

#542 Update dependencies
  composer.lock
Labels: scope:distribution

#548 Update Composer lock file
  composer.lock
Labels: scope:distribution

#549 Update Composer lock file
  composer.lock
Labels: scope:distribution

#550 Release v2.8.0
  composer.json
  composer.lock
Labels: scope:distribution
