Repository wp-cli/wp-cli-bundle, pull requests merged in 2025-04, with the labels that each got.

#713 Add missing manifest file to build commits
  .github/workflows/deployment.yml
Labels: scope:distribution

#714 Update wp-cli framework
  composer.lock
  features/bootstrap.feature
  features/config.feature
  features/requests.feature
Labels: scope:framework

#715 Update wp-cli framework
  composer.lock
Labels: scope:framework

#716 Update wp-cli framework
  composer.lock
Labels: scope:framework

#717 Fix Gherkin lint issues
  features/cli.feature
Labels: scope:testing

#718 Update wp-cli framework
  composer.lock
Labels: scope:framework

#730 Update wp-cli framework
  composer.lock
Labels: scope:framework

#742 Update wp-cli framework
  composer.lock
Labels: scope:framework

#743 Fix broken phar tests
  features/package.feature
  utils/make-phar.php
Labels: scope:testing

#744 Update wp-cli framework
  composer.lock
Labels: scope:framework
