Repository wp-cli/wp-cli-bundle, pull requests merged in 2025-03, with the labels that each got.

#691 Update wp-cli framework
  composer.lock
Labels: scope:framework

#692 Add manifest.json file for builds
  .github/workflows/deployment.yml
Labels: enhancement, scope:distribution

#693 Update wp-cli framework
  composer.lock
Labels: scope:framework

#695 Update wp-cli framework
  composer.lock
  features/cli.feature
Labels: scope:framework

#696 Deployment: Fix `FILENAME` env var
  .github/workflows/deployment.yml
Labels: scope:distribution

#697 Update framework with all dependencies
  .github/workflows/update-framework.yml
  composer.lock
Labels: scope:distribution

#699 Update wp-cli framework
  composer.lock
Labels: scope:framework

#701 Update wp-cli framework
  composer.lock
Labels: scope:framework

#702 Update wp-cli framework
  composer.lock
Labels: scope:framework

#704 Update wp-cli framework
  composer.lock
Labels: scope:framework

#705 Update wp-cli framework
  composer.lock
Labels: scope:framework

#707 Update wp-cli framework
  composer.lock
Labels: scope:framework

#708 Update wp-cli framework
  composer.lock
Labels: scope:framework

#710 Update wp-cli framework
  composer.lock
Labels: scope:framework

#712 Update wp-cli framework
  composer.lock
Labels: scope:framework
